##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: talosdevbox_web
        restart: always
        image: talosdigital/magento2devbox-web:latest
        volumes:
          - "./shared/webroot:/var/www/magento2"
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "./shared/logs/apache2:/var/log/apache2"
          - "./shared/logs/php-fpm:/var/log/php-fpm"
          - "./shared/.magento-cloud:/home/magento2/.magento-cloud"
        expose:
          - "9000"
        ports:
          - "80:80"
          - "4022:22"
          - "9000:9000"

    db:
        container_name: talosdevbox_db
        restart: always
        image: mysql:5.6
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=mysql
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

