version: '2'
services:
    web:
        container_name: talosdevbox_web
        image: talosdigital/magento2devbox-web:php5.6
        volumes:
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "./shared/logs/apache2:/var/log/apache2"
          - "./shared/logs/php-fpm:/var/log/php-fpm"
          - talosdevbox_sync:/var/www/magento2:nocopy
        expose:
          - "9000"
        ports:
          - "80:80"
          - "4022:22"

    db:
        container_name: talosdevbox_db
        image: mysql:5.6
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=mysql
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

volumes:
  talosdevbox_sync:
    external: true
