version: '2'
services:
    web:
        container_name: talosdevbox_web
        image: talosdigital/magento2devbox-web:latest
        volumes:
          - ~/.composer:/home/magento2/.composer:delegated
          - ~/.ssh:/home/magento2/.ssh:cached
          - ./shared/logs/apache2:/var/log/apache2:delegated
          - ./shared/logs/php-fpm:/var/log/php-fpm:delegated
          - ./shared/apache2:/etc/apache2/host-config:cached
          - ./shared/webroot:/var/www/magento2:delegated
          - ./shared/webroot/app:/var/www/magento2/app:consistent
        expose:
          - "9000"
        ports:
          - "80:80"
          - "443:443"
          - "4022:22"

    db:
        container_name: talosdevbox_db
        image: mysql:5.6
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=mysql
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"
